### ISSUE TITLE
Odd speed boost bug when noclipping

### ISSUE THREAD

**Issue by Ash5173** [fabiangreffrath/crispy-doom#1077] opened 2023-07-03 15:37 UTC
I noticed that when turning on noclip, any time I ran off a ledge or even just going down the smallest of steps, you get a pretty noticeable speed boost. Definitely a minor one, but figured it was worth reporting. I guess maybe it could make moving through a map while play testing or just checking it out slightly more difficult since you won't expect the speed boost.

Crispy Doom Version: 6.0 (Also observed in many old versions as well)

OS: Windows 10

**Comment by fabiangreffrath** [comment] 2023-07-03 16:57
Hi, Crispy supplies `onground` movement rules even mid-air when the NOCLIP cheat is active. However, there shouldn't be any speedup compared to uncheated movement - at least that wouldn't be intentional. 

https://github.com/fabiangreffrath/crispy-doom/blob/607833cf6912912608d5057f6fceffdd0203ec50/src/doom/p_user.c#L164

**Comment by kitchen-ace** [comment] 2023-08-14 21:17
You definitely get a speed boost in air with noclip, and have since Crispy first had air control while noclipping. I actually thought it was intended for whatever reason ¯\\\_(ツ)\_/¯

Here's a test map you can use to compare, that's just a platform to run off of, with some coloured floors. You can clearly see how much further you go in the air when noclipping.

My complete guess is it's something related to the same code that enables wallrunning, and that P_SlideMove is applying movement twice per tic. 
https://www.doomworld.com/forum/topic/87199-the-doom-movement-bible/?tab=comments#comment-1587754

[noclip.wad.zip](https://github.com/fabiangreffrath/crispy-doom/files/12339642/noclip.wad.zip)

**Comment by fabiangreffrath** [comment] 2023-08-15 06:53
I think the cause is that there is thrust applied to accelerate, because `onground == true` in `P_MovePlayer()`, but there is never friction applied to decellerate, because `mo->z > mo->floorz` in `P_XYMovement()`.

https://github.com/fabiangreffrath/crispy-doom/blob/bc3645ce0517c08501a04bbabf62faa59fc673c0/src/doom/p_mobj.c#L260-L261

**Comment by fabiangreffrath** [comment] 2023-08-15 06:58
Does this normalize zhings for you? (Sorry, can't test right now)

```patch
--- a/src/doom/p_mobj.c
+++ b/src/doom/p_mobj.c
@@ -257,6 +257,7 @@ void P_XYMovement (mobj_t* mo)
     if (mo->flags & (MF_MISSILE | MF_SKULLFLY) )
        return;         // no friction for missiles ever

+  if (!player || !(player->mo->flags & MF_NOCLIP))
     if (mo->z > mo->floorz)
        return;         // no friction when airborne

```

**Comment by kitchen-ace** [comment] 2023-08-15 14:24
Yep, that fixes it!

>(Sorry, can't test right now)

It's a several-years old, very negligible bug -- there's no hurry :)

**Comment by SoDOOManiac** [comment] 2023-08-18 07:04
>Yep, that fixes it!
I'd love to see this fix merged soon to include it in my fork release :)

**Closed** 2023-08-20 15:05 UTC
