### ISSUE TITLE
Crash after loading any map in Sunder.wad

### ISSUE THREAD

**Issue by JNechaevsky** [fabiangreffrath/crispy-doom#408] opened 2019-04-24 16:26 UTC
### Background

Version of Crispy Doom: 5.5.2 (both released and custom git build)

Operating System and version: Windows 10 LTST x64 / Debian x32

Game: Doom

Any loaded WADs and mods (please include full command line): 
`./crispy-doom -file sunder.wad -warp 01 `

### Bug description

Crispy is crashing after trying to load any of 14 maps of [sunder.wad](https://www.doomworld.com/vb/thread/46002). Last messages in console output are:

```
PadRejectArray: REJECT lump too short to pad! (23762 > 16)
Ошибка сегментирования (Segmentation fault)
```

But no, `gdb` showing a real reason, have a look:

```
julian@energia-wm:~/crispy-doom/src$ gdb --args ./crispy-doom -file sunder.wad
GNU gdb (Ubuntu 8.1-0ubuntu3) 8.1.0.20180409-git
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "i686-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./crispy-doom...done.
(gdb) run
Starting program: /home/julian/crispy-doom/src/crispy-doom -file sunder.wad
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/i386-linux-gnu/libthread_db.so.1".
                           Crispy Doom 5.5.2
Z_Init: Init zone memory allocation daemon. 
zone memory: 0xb4bf8010, 2000000 allocated for zone
Using /home/julian/.local/share/crispy-doom/ for configuration and saves
V_Init: allocate screens.
M_LoadDefaults: Load system defaults.
saving config in /home/julian/.local/share/crispy-doom/default.cfg
W_Init: Init WADfiles.
 adding DOOM2.wad
 merging sunder.wad !
This is not a valid dehacked patch file!
  loaded 1 DEHACKED lumps from PWAD files.
===========================================================================
                         DOOM 2: Hell on Earth
===========================================================================
 Crispy Doom is free software, covered by the GNU General Public
 License.  There is NO warranty; not even for MERCHANTABILITY or FITNESS
 FOR A PARTICULAR PURPOSE. You are welcome to change and distribute
 copies under certain conditions. See the source for more information.
===========================================================================
I_Init: Setting up machine state.
[New Thread 0xb4bf7b40 (LWP 30256)]
[New Thread 0xa43f6b40 (LWP 30257)]
[New Thread 0x943b5b40 (LWP 30258)]
I_SDL_InitSound: use_libsamplerate=1, but libsamplerate support not compiled in.
Failed to get I/O port permissions for 0x388: Operation not permitted
	You may need to run the program as root in order
	to acquire I/O port permissions for OPL MIDI playback.
OPL_Init: Using driver 'SDL'.
I_InitSound: SDL audio driver is pulseaudio
NET_Init: Init network subsystem.
M_Init: Init miscellaneous info.
R_Init: Init DOOM refresh daemon - [                                            ................................................
P_Init: Init Playloop state.
S_Init: Setting up sound.
D_CheckNetGame: Checking network game status.
startskill 2  deathmatch: 0  startmap: 1  startepisode: 1
player 1 of 1 (1 nodes)
Emulating the behavior of the 'Doom 1.9' executable.
HU_Init: Setting up heads up display.
ST_Init: Init status bar.
warning: Error reading shared library list entry at 0x2080
warning: Error reading shared library list entry at 0x3570
P_SetupLevel: MAP01 (sunder.wad), Normal, Time 0:00:00, Total 0:00:00, Doom map format, normal BSP nodes.
PadRejectArray: REJECT lump too short to pad! (23762 > 16)

Thread 1 "crispy-doom" received signal SIGSEGV, Segmentation fault.
R_DrawColumnInCache (patch=0xc3d4ba9a, cache=0xb591d157 "", originy=0, 
    cacheheight=64, marks=0xd53750 "") at r_data.c:208
208	    while (patch->topdelta != 0xff)
(gdb) 
```

**Comment by JNechaevsky** [comment] 2019-04-24 17:20
Uncommenting this condition seems to eliminate crashing:
https://github.com/fabiangreffrath/crispy-doom/blob/master/src/doom/r_data.c#L311

```
	for ( ; x<x2 ; x++)
	{
	    // Column does not have multiple patches?
	    // [crispy] generate composites for single-patched columns as well
---	    /*
	    if (collump[x] >= 0)
		continue;
---	    */
```

But also preventing wall textures from being loaded. Maybe this is the case...

**Comment by fabiangreffrath** [comment] 2019-04-25 07:29
Dammit, I know for sure that Sunder once worked!

**Comment by fabiangreffrath** [comment] 2019-04-25 08:06
What I have digged out so far:
- The problem starts when I unconditionally create composites for each texture present in the map in R_PrecacheLevel()
- The first texture is "AASHITTY" which is composed of 1 patch called "BODIES"
- There are two lumps of this name in the WAD, one seems to be a valid patch - the other one with the higher index does not.
- We are then trying to create a composite texture of a lump that is apparently not a patch.

```
(gdb) p *textures[0]
$18 = {name = "AASHITTY", width = 64, height = 64, index = 0,
  next = 0x2b8ef54, patchcount = 1, patches = {{originx = 0, originy = 0,
      patch = 2952}}}

(gdb) p *lumpinfo[2952]
$21 = {name = "BODIES\000", wad_file = 0x2ac1380, position = 2092076,
  size = 4096, cache = 0x2bffc24, next = 2711}
(gdb) p *(patch_t*)0x2bffc24
$24 = {width = 20375, height = 407, leftoffset = 0, topoffset = 512,
  columnofs = {251727854, 244187917, -1929253362, 1684301160, 33689444,
    1330581249, 234881024, -1734676857}}

(gdb) p W_CheckNumForNameFromTo("BODIES", 2951, 0)
$20 = 2711
(gdb) p *lumpinfo[2711]
$22 = {name = "BODIES\000", wad_file = 0x2ac0058, position = 13291052,
  size = 8776, cache = 0x0, next = -1}
(gdb) p W_CacheLumpNum(2711, PU_STATIC)
$25 = (void *) 0x38b3a50
(gdb) p *(patch_t*)0x38b3a50
$26 = {width = 64, height = 128, leftoffset = 31, topoffset = 123,
  columnofs = {264, 397, 530, 663, 796, 929, 1062, 1195}}
```

**Comment by fabiangreffrath** [comment] 2019-04-25 08:32
```
--- a/src/doom/r_data.c
+++ b/src/doom/r_data.c
@@ -292,6 +292,8 @@ void R_GenerateComposite (int texnum)
         i<texture->patchcount;
         i++, patch++)
     {
+       const unsigned long patchsize = W_LumpLength(patch->patch);
+
        realpatch = W_CacheLumpNum (patch->patch, PU_CACHE);
        x1 = patch->originx;
        x2 = x1 + SHORT(realpatch->width);
@@ -312,6 +314,10 @@ void R_GenerateComposite (int texnum)
            if (collump[x] >= 0)
                continue;
            */
+
+           // [crispy] never read past the patch lump boundaries
+           if ((unsigned long)LONG(realpatch->columnofs[x-x1]) > patchsize)
+               continue;

            patchcol = (column_t *)((byte *)realpatch
                                    + LONG(realpatch->columnofs[x-x1]));

```

**Comment by fabiangreffrath** [comment] 2019-04-25 11:18
> * The problem starts when I unconditionally create composites for each texture present in the map in R_PrecacheLevel()

Confirmed: The WAD loads fine in Crispy Doom 5.3 and starts crashing once I apply https://github.com/fabiangreffrath/crispy-doom/commit/c8abc70536b216d0311e2d5750a9ccea3bb0ceeb#diff-1fd5c512dc24ef2afc481a654c69d4cb

Now, the question is why the crash never happened in-game? Is the texture never visible at all? And why do other source ports like PrBoom+ find the correct patch-formatted "BODIES" lump instead of the malformed one?

**Comment by fabiangreffrath** [comment] 2019-04-25 12:20
On the other hand, knowing that AASHITTY is just a dummy texture that is never meant to be actually rendered, the fix could be as simple as this:
```
--- a/src/doom/r_data.c
+++ b/src/doom/r_data.c
@@ -1343,7 +1343,7 @@ void R_PrecacheLevel (void)
            continue;

        // [crispy] precache composite textures
-       R_GenerateComposite(i);
+       if (i > 0) R_GenerateComposite(i); // [crispy] skip AASHITTY

        texture = textures[i];

```

**Comment by JNechaevsky** [comment] 2019-04-25 12:41
Hmm. `MAP16` of Doom II comes to mind, do you remember red building with four doors, where one of them is false-door? ([pic from inside](https://i.ytimg.com/vi/39aJIyy8cws/maxresdefault.jpg), can't make my own from work).

 AFAIR, behild those doors `AASTINKY` (pile of skulls) is placed. Silly question, but is it safe todon't gererate composite textures for them after all?

I will gladly check everything, but only in the evening.

**Comment by fabiangreffrath** [comment] 2019-04-25 13:06
> don't gererate composite textures for them after all

This is only about precaching. If the texture is encountered in-game, the composite will be created nevertheless. That's why I asked what would happen in-game if the texture came into vision and why other ports that precache textures don't suffer from the non-patch lump of the same name as the one that composes AASTINKY.

**Comment by fabiangreffrath** [comment] 2019-04-25 16:00
I'll need to add a check for this, but unfortunately `R_InitFlats()` is called after `R_InitTextures()`.

**Comment by JNechaevsky** [comment] 2019-04-25 18:36
But with this approach everything seems to be fine:

```
        // [crispy] precache composite textures
-       R_GenerateComposite(i);
+       if (i > 0) R_GenerateComposite(i); // [crispy] skip AASHITTY
```

`BODIES` flat working fine ([screenshot](https://user-images.githubusercontent.com/21193394/56759417-95ac3f80-67a1-11e9-8763-138d6a159791.png), this place in [doom builder](https://user-images.githubusercontent.com/21193394/56759548-e3c14300-67a1-11e9-812e-80002185ba7f.png)), and also fine in `MAP16` of HoE ([screenshot](https://user-images.githubusercontent.com/21193394/56759627-09e6e300-67a2-11e9-87c5-0029acd53422.png)).

**Comment by fabiangreffrath** [comment] 2019-04-25 19:58
Yes, but this still butters over the symptoms. The underlying issue is that a flat slipped into the texture composite creation process and I just need some additional checks to prevent this.

**Comment by JNechaevsky** [comment] 2019-04-25 20:27
I'm afraid further investigation in the code is too difficult for me, I will not be able to suggest anything useful. Except one thing, probably - maybe I should create a map or bunch of maps with such errors like same names for patches/flats, medusas, broken patches and something? It could be help in future.

**Comment by fabiangreffrath** [comment] 2019-04-25 20:44
I have an idea which works. More on that tomorrow...

> I should create a map or bunch of maps with such errors like same names for patches/flats, medusas, broken patches and something? It could be help in future.

This would be worth gold!

**Comment by JNechaevsky** [comment] 2019-04-25 21:08
> This would be worth gold!

Excellent! Please help me with collecting a possible list of cases / bugs then. I'm not familiar with existing mods/TCs to check, but know how to reproduce mostly all bugs. Or maybe it will be even better to collect as much cases as possible, i.e. not only mapping related? 

I think it will be a good idea to collect all cases in Google Table, because here, in messages, we may loose something.

**Comment by fabiangreffrath** [comment] 2019-04-26 06:21
Of course, the best fix for this would be to finally implement proper namespaces for lumps. But this would be a rather invasive change with potential for even more bugs and regressions. What we have here should be the most dangerous case of lump name mix-up, i.e. mistaking a flat for a patch. And if I can fix this with a 5-lines patch, I am okay with it.

**Closed** 2019-04-26 18:23 UTC
Labels: bug, patch, pending

**Comment by JNechaevsky** [comment] 2019-04-28 21:30
Have to correct myself about `AASHITTY` texture on MAP16. No, it's not `AASHITTY`, it's a `SP_FACE2` textue which is using `BODIES` as a patch ([screenshot](https://user-images.githubusercontent.com/21193394/56870285-ecba4a80-6a15-11e9-8f93-b332f017005d.png)). I should know that "first" texture and "first" patch is a different things. :persevere:

**Comment by fabiangreffrath** [comment] 2019-04-29 09:07
Indeed, I think it is not even possible to select `AASHITTY` as a texture, because it would have index `0` and this is in turn reserved for "no texture" -- or something like this. :wink:

**Comment by JNechaevsky** [comment] 2019-04-29 13:12
AFAIR, "no texture" is a `-` in both code and map editors. :relaxed:
