### ISSUE TITLE
Frequent crashes

### ISSUE THREAD

**Issue by Leader-of-Freedonia** [fabiangreffrath/crispy-doom#1079] opened 2023-07-23 17:23 UTC
### Background

Version of Crispy Doom: 6.0.0

Operating System and version: Windows 10 22H2, 19045.3208

Game: (Doom/Heretic/Hexen/Strife/other) Ultimate Doom, Doom 2

Any loaded WADs and mods (please include full command line): DOOM.WAD, DOOM2.WAD

### Bug description

Observed behavior: After 11-14 minutes of playtime, game freezes, then exits (no error message). Doom 1 usually crashes at E1M3, Doom 2 usually at MAP4.

Expected behavior: No crashes.

Edit: The game doesn't crash when music is turned off. I normally use music packs of SC-55 recordings.

**Comment by mikeday0** [comment] 2023-07-24 03:06
This is a duplicate of #1066 and #1049. This is an issue with SDL_Mixer FLAC looping. It has been fixed there, but a new release of SDL_Mixer hasn't happened yet. In the meantime as a workaround you can use the ogg version of the musicpacks.

**Closed by mikeday0** 2023-07-24 03:06 UTC
