### ISSUE TITLE
Level Names Incorrect

### ISSUE THREAD

**Issue by snoggie1487** [fabiangreffrath/crispy-doom#618] opened 2020-05-22 17:49 UTC
### Background

Version of Crispy Doom: 

Operating System and version: 5.8.0

Game: (Doom/Heretic/Hexen/Strife/other)  Plutonia

Any loaded WADs and mods (please include full command line): -iwad WADs/plutonia.wad

### Bug description

Observed behavior: When playing Plutonia, TNT, Final Doom, Master Levels, ETC... Level names are set to their counterparts from the original Doom 2 (Plutonia MAP01 is Entryway) This is not an issue with my wad, I tried these same wads with chocolate doom and the level names are correct

Expected behavior: Plutonia MAP01 should be Congo

**Comment by tpoppins** [comment] 2020-05-23 05:53
Confirmed: forward slashes **/** in path produce this behavior.

@snoggie1487: use the backslash **\** instead, i.e. 
-iwad WADs\plutonia.wad

You are on Windows, right?

**Comment by fabiangreffrath** [comment] 2020-05-23 15:46
Indeed, this seems to be a duplicate of https://github.com/chocolate-doom/chocolate-doom/issues/1271

I'll file a PR for this some day...

**Closed** 2020-05-26 04:38 UTC
Labels: duplicate, upstream
