### ISSUE TITLE
Items can "shine" through the floors

### ISSUE THREAD

**Issue by JNechaevsky** [fabiangreffrath/crispy-doom#250] opened 2018-01-03 18:23 UTC
While mouse look. 

Example screenshots:
- E1M1 Hangar №1: http://screenshot.ru/upload/images/2018/01/03/items_163922.png
- E1M1 Hangar №2: http://screenshot.ru/upload/images/2018/01/03/items_2763c3.png
- Surprisingly, [PrBoom+](http://screenshot.ru/upload/images/2018/01/03/items_pr369a3.png) and [my project](http://screenshot.ru/upload/images/2018/01/03/items_rd8a6eb.png) are also affected.

**Possible explanation**

I think this is not exactly a mouse-look related, items are "shining" in case of... Kinda hard to explain, but I'll try: in case if the most far line of the sector is partially goes out of screen bounds. Top bounds in this case. 

At the moment, I don't have any ideas, is it `R_DrawPlanes` or `R_DrawSprite` issue, and which additional maths should be done. Need to investigate.

**Comment by JNechaevsky** [comment] 2018-01-03 20:13
Nope, I can't handle this. Experements with `viewheight` in https://github.com/fabiangreffrath/crispy-doom/blob/master/src/doom/r_things.c#L1275 giving some results, but it seems to be wrong way to go.

**Comment by fabiangreffrath** [comment] 2018-01-03 21:00
This is probably a duplicate of https://github.com/fabiangreffrath/crispy-doom/issues/114

**Comment by JNechaevsky** [comment] 2018-01-05 11:41
Probably so, but probably not, because in that case thing is slightly clipped inside wall segment.
In my case things are palced far enough from segments: [screenshot 1](http://screenshot.ru/upload/images/2018/01/05/1bb2ce.png) and [screenshot 2](http://screenshot.ru/upload/images/2018/01/05/24b3a1.png).

I belive this case is caused by mouse look and theoretically it can be fixed by recuding looking down's aplitude to such ammount, when horizont can't be outside of top screen bounds, but this is a bad way to go.

I'll try to dig into the Heretic code, maybe fix can be found there.

**Comment by JNechaevsky** [comment] 2018-01-05 13:51
Small additional chord: items are not shinig throug the solid one sided walls. It's kinda ovibivios, but makes some sence if fact, that this could be an issue of `R_PointOnSegSide` or `R_RenderMaskedSegRange`.
- http://screenshot.ru/upload/images/2018/01/05/directiond8414.png

**Comment by fabiangreffrath** [comment] 2018-01-08 08:42
Does the patch I propose here fix the issue?

https://github.com/fabiangreffrath/crispy-doom/issues/79#issuecomment-165358190

**Comment by JNechaevsky** [comment] 2018-01-08 09:04
Nope, not working for this case.

**Comment by JNechaevsky** [comment] 2018-01-08 10:31
Intetesting, extending condition https://github.com/fabiangreffrath/crispy-doom/blob/master/src/doom/r_segs.c#L678 to:

```
        if (frontsector->floorheight > backsector->floorheight
        ||  viewz > backsector->floorheight) // <-- i.e. extending to this
```

Fixes _half_ of this case. Now I no longer see "bleeding" items at some angles, but at some they are still appearing. Wonder what else should be done, probably another whole condition.

**Comment by JNechaevsky** [comment] 2018-01-08 14:32
I have a feeling that operating with `R_StoreWallRange` is a proper way (thanks for pointing out!) and also have a little theory which will try to explain. Some schematic mockups:

This is a proper case, two sided line is accounted and it making a proper clipping. In the code, clipping starts in one of [these conditions](https://github.com/fabiangreffrath/crispy-doom/blob/master/src/doom/r_segs.c#L674):
![](http://screenshot.ru/upload/images/2018/01/08/ok0dd44.png)

And this one is not. In this case items are bleeding through the floor. Two-sided line is out from field of view and not rendered. Thus, clipping code conditions are not working properly.
![](http://screenshot.ru/upload/images/2018/01/08/not-ok52e7f.png)

Since in vanilla Doom it was not possible to look down and invoke cases like this, there was no necessity for additional clipping conditions. Raven devs may simply don't notify this. Probably...

I think, additional checking should be done in `if (!backsector)` section ([here](https://github.com/fabiangreffrath/crispy-doom/blob/master/src/doom/r_segs.c#L632)). It's a fact, that the bottles are placed in `backsector`, and this `backsector` is not rendered as level geometry, but items still rendered.

Maybe I'm copletely wrong, thoug.

**Comment by fabiangreffrath** [comment] 2018-01-08 19:54
Hm, is it possible we see the two bottles *underneath* the two-sided line?

**Comment by JNechaevsky** [comment] 2018-01-08 21:20
I belive it is not possible by the law of perspective: that two-sided magenta line will always "cover" bottels. To see those bottles underneath the line, they must be placed under the floor.

I even can't imagine any possible situations where it can happen. In Doom engine player is never able to get below the floor. The only place that comes to mind is Plutonia's MAP25 ([screenshot](http://screenshot.ru/upload/images/2018/01/09/plutonia68a1c.png)) with small anomaly in BLOCKMAP, but even so this is not the case - player is standing in nearest&lowest floor.

But again, bottles will not bleed if between them and player will be solid wall or even small pillar (with two-sided lines).

This case is start to turning into a mind-explosion. Maybe we should just close it sooner or later?
In theory everything seems to be clear, but I can't achive fix in the code. Dang.

**Comment by fabiangreffrath** [comment] 2018-01-08 21:39
Sprite clipping in Doom is a fucking mystery, that's for sure.

**Comment by JNechaevsky** [comment] 2018-03-09 17:57
I still can't calm down because of this. Looks likes everything is playing _against us_ here, starting from sprites + sectors + screenblocks rendering order and ending with common sense.

More of that, my patch is screwed up in one surprisingly well-seen place (MAP19, The Citadel), so please do not apply it until we'll have a better or additional solution:

- http://screenshot.ru/upload/images/2018/03/09/DOOM0113e73.png

**Comment by JNechaevsky** [comment] 2018-03-09 18:11
I'm currently testing this:

```
        // two sided line
        ds_p->sprtopclip = ds_p->sprbottomclip = NULL;
        ds_p->silhouette = 0;

        if (frontsector->floorheight > backsector->floorheight)
        {
            ds_p->silhouette = SIL_BOTTOM;
            ds_p->bsilheight = frontsector->floorheight;
        }
        else if (backsector->floorheight > viewz
+++     || backsector->floorheight < viewz)
        {
            ds_p->silhouette = SIL_BOTTOM;
            ds_p->bsilheight = INT_MAX;
            // ds_p->sprbottomclip = negonearray;
        }
```

As previously, it does not fixes this issue completely, but again hides notable "leaking". And again, I have no idea how this is actially working. The best thing I can do - test it as much as possible.

**Comment by fabiangreffrath** [comment] 2020-03-26 11:34
I am closing some old issues that I consider irrelevant by now. Feel free to reopen with a comment if you disagree.

**Closed by fabiangreffrath** 2020-03-26 11:34 UTC
Labels: bug, rendering
