### ISSUE TITLE
Nightmare Mode uses easier BFG edition Nightmare on my original Doom2.wad sometimes.

### ISSUE THREAD

**Issue by Pete-Lawrence** [fabiangreffrath/crispy-doom#196] opened 2017-05-04 21:21 UTC
[doomsav1.zip](https://github.com/fabiangreffrath/crispy-doom/files/977584/doomsav1.zip)

If you load this save, it uses the easier Nightmare mode from BFG edition despite running on the original Doom2.wad. It continues to stay on BFG Nightmare until you save again and reopen the game.

**Comment by fabiangreffrath** [comment] 2017-05-05 06:39
I am sorry, but I don't quite understand this yet.

What exactly is "BFG Nightmare" and how exactly did you produce this savegame (i.e. on which port with which settings)?

**Comment by JNechaevsky** [comment] 2017-05-05 06:43
Probably was meant that in BFG Edition, Nightmare skill level works a little bit defferent: there are no fast monster's missilies and no fast demons.

In case of making a savegame in BFG Edition (NM skill), it acts same in NON-BFG Edition.

@Pete-Lawrence, is it so? Please confirm.

**Comment by Pete-Lawrence** [comment] 2017-05-05 15:25
I don't have BFG Edition, it just happens to have it on the BFG edition style Nightmare for some reason, no idea how I did it.

I'm on Crispy Doom 4.0. I found to revert back to regular nightmare after loading the save is to save again, new game > nightmare. load game > then load your new save.

**Comment by Pete-Lawrence** [comment] 2017-05-05 21:02
It could possibly be this? https://www.youtube.com/watch?v=Owvm12a4KgM

**Comment by Zodomaniac** [comment] 2017-05-06 11:57
@Pete-Lawrence there's even an opposite effect https://www.youtube.com/watch?v=HrBR35gHmDc

**Comment by fabiangreffrath** [comment] 2017-05-06 20:40
Yes, this is indeed a very old and well-known Vanilla bug. I have already fixed the worst consequence of it, i.e. the state duration of the demons becoming 0 which results in the game locking up. However, I have so far decided to let the bug itself unfixed, since it is somehow typical to Vanilla and some weird circumstances may require it (who knows, some in-game demos recorded with this glitch or whatever).

But, as it seems this causes way too much confusion and is actually unexpected behavior. Apart from this, it has been fixed in other advanced ports as well, starting with Boom. I'll fix it with the next commit!

**Closed** 2017-05-06 21:09 UTC
