### ISSUE TITLE
Graphical glitch of the near-sector-edge sprite 'piercing the ground'

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#114] opened 2016-06-13 18:34 UTC
![doom02](https://cloud.githubusercontent.com/assets/15119473/16018762/985a3aba-31ae-11e6-99c2-15ced7ae9f9b.png)

**Comment by fabiangreffrath** [comment] 2016-06-13 19:50
Sprite clipping at flats is tricky in the Doom engine, but I have an idea. Could you please send me a savegame of this by e-mail? I am sure it looks exactly the same in Choco, right?

**Comment by Zodomaniac** [comment] 2016-06-13 20:00
Emailed you the savegame. Right, it's the same in Choco.

**Comment by Zodomaniac** [comment] 2016-06-17 17:34
Here is that savegame for your convenience. To see that glitch in Choco, take a step back to see that dead imp leg popping through the ground.
[doomsav5.zip](https://github.com/fabiangreffrath/crispy-doom/files/320998/doomsav5.zip)

**Comment by fabiangreffrath** [comment] 2016-06-17 17:37
Thanks, I can see it!

**Comment by fabiangreffrath** [comment] 2016-06-24 17:47
What we can see on the screenshot is that the sprite is actually correctly clipped by the seg, i.e. the part of the wall surrounding the lava pit that we cannot see because it is obstructed by the floor. This kind of clipping should be completely sufficient as long as you are not allowed to look up or down. But in Crispy, you are.

Could you maybe check if you could reproduce a similar situation in Heretic?

**Comment by fabiangreffrath** [comment] 2016-06-25 11:58
It looks like the Imp is stuck mid-air in the wall surrounding the lava pit, it does neither lie on the ground inside the pit nor on the floor above it. How did you manage to get this?

**Comment by Zodomaniac** [comment] 2016-06-25 21:16
>How did you manage to get this?

A friend of mine says I'm a natural born beta-tester))
I also once got a similar situation in Army of Darkness Doom.

**Comment by fabiangreffrath** [comment] 2016-06-25 21:52
Actually, this is a duplicate of https://github.com/chocolate-doom/chocolate-doom/issues/734 and I think it should be solved upstream, if at all. The discussion in this bug report is really relevant and I doubt there is much that we can add in this thread. I am closing it as a duplicate, thus.

**Comment by fabiangreffrath** [comment] 2016-06-25 21:53
Damn, wrong bug...

**Comment by fabiangreffrath** [comment] 2016-07-13 18:54
Confirmed that this bug is also present in Heretic, which is the first Doom-based game to support view pitch and on which I based my implementation.


[heretic-sprite-clipping.wad.zip](https://github.com/fabiangreffrath/crispy-doom/files/362233/heretic-sprite-clipping.wad.zip)

**Comment by AXDOOMER** [comment] 2017-02-01 17:14
It happens whenever a sprite is close enough to a wall that it goes through it. You don't need to be able to look up and down. 

For example, if an imp has a radius of 16 but the sprite is 40 wide, then 4 pixels can "enter" inside the wall. This 4 pixels can appear because of glitches. It can cause any kinds of glitches. https://www.youtube.com/watch?v=TEHfo6HUrMo

This is easier to do by placing fixed things on your own map. See also the issue that I referenced in Doom Retro.

**Comment by fabiangreffrath** [comment] 2017-02-10 11:21
> See also the issue that I referenced in Doom Retro.

Which issue was that?

**Comment by AXDOOMER** [comment] 2017-02-10 18:05
Github had put a reference just above my comment. Here's the link:  https://github.com/bradharding/doomretro/issues/97

**Comment by fabiangreffrath** [comment] 2017-02-12 15:21
I see, thank you!

However, I am not actually "working on a solution", but I think I found a fix per incident here that improves sprite clipping in certain situations:
https://github.com/fabiangreffrath/crispy-doom/issues/79#issuecomment-165358190

I am I bit too coward, though, to apply it now as it is. It still needs further investigation...

**Comment by fabiangreffrath** [comment] 2020-03-26 11:33
I am closing some old issues that I consider irrelevant by now. Feel free to reopen with a comment if you disagree.

**Closed by fabiangreffrath** 2020-03-26 11:33 UTC
Labels: rendering, upstream
