### ISSUE TITLE
PC speaker effects are not working

### ISSUE THREAD

**Issue by Shade-Of-Fear** [fabiangreffrath/crispy-doom#748] opened 2021-05-23 13:15 UTC
### Background

Version of Crispy Doom: 5.10.1 and 5.10.0

Operating System and version: Windows 7 6.1.7601 x64

Game: Doom

Any loaded WADs and mods (please include full command line): doom.wad only, opening from ZDL 3-1.1 using Crispy Doom as a source port and also putting the doom.wad directly in the Crispy Doom folder and launching crispy-doom.exe.

### Bug description

Observed behavior: When using crispy-doom-setup.exe to configure "PC speaker effects" from the "Configure Sound" options, save the settings and then start crispy-doom.exe either directly or from ZDL launcher, Doom starts, the MIDI music plays, but the sound effects are not playing. (Menu navigation, in game shooting, collecting items, waking up monsters...)

Expected behavior: The "PC speaker effects" should play the old sounds :)

I've tried using chocolate-doom.exe version 3.0.1 and the old PC speaker effects are playing normally. So I think it's not something with my PC or OS.

**Comment by fabiangreffrath** [comment] 2021-05-26 11:40
Does it work with the dev build from http://latest.chocolate-doom.org/ ?

**Comment by Shade-Of-Fear** [comment] 2021-05-26 16:13
I've just tried chocolate-doom-20210526-win32 and crispy-doom-20210526-win32.
Both chocolate and crispy don't work.

**Comment by drfrag666** [comment] 2021-06-05 19:27
They don't work in RUDE either at least since february 2020 so it's old. i think this should be investigated in old Crispy releases.

**Comment by drfrag666** [comment] 2021-06-11 19:49
I've done some investigation and the last version with them working is 5.3.
https://github.com/fabiangreffrath/crispy-doom/releases/tag/crispy-doom-5.3

**Comment by drfrag666** [comment] 2021-06-11 22:04
Changing music to midi/mp3/ogg/flac makes them work in the latest release.
I believe there were some commits related to music packs, could be one of those.

**Comment by Shade-Of-Fear** [comment] 2021-06-12 10:46
Yes, I can confirm on my PC.
The sound effects work in crispy-doom-5.3
They work in 5.10.1 if music is set to midi/mp3/ogg/flac.

**Comment by drfrag666** [comment] 2021-06-12 11:23
It's a duplicate of this Choco issue: https://github.com/chocolate-doom/chocolate-doom/issues/1184

**Comment by mikeday0** [comment] 2021-06-15 14:24
I think the issue is that both the opl emulation and the pc speaker emulation register a callback with `Mix_SetPostMix`. SDL Mixer only allows for one `Mix_SetPostMix` callback. I believe the fix may be as simple as changing these calls to `Mix_RegisterEffect` with `MIX_CHANNEL_POST` as the channel. There's no limit on the number of callbacks when using `Mix_RegisterEffect`.

**Comment by mikeday0** [comment] 2021-06-16 01:22
This seems to fix the problem:

```diff
--- a/pcsound/pcsound_sdl.c
+++ b/pcsound/pcsound_sdl.c
@@ -53,7 +53,7 @@ static int phase_offset = 0;
 
 // Mixer function that does the PC speaker emulation
 
-static void PCSound_Mix_Callback(void *udata, Uint8 *stream, int len)
+static void PCSound_Mix_Callback(int chan, void *stream, int len, void *udata)
 {
     Sint16 *leftptr;
     Sint16 *rightptr;
@@ -236,7 +236,7 @@ static int PCSound_SDL_Init(pcsound_callback_func callback_func)
     current_freq = 0;
     current_remaining = 0;
 
-    Mix_SetPostMix(PCSound_Mix_Callback, NULL);
+    Mix_RegisterEffect(MIX_CHANNEL_POST, PCSound_Mix_Callback, NULL, NULL);
 
     return 1;
 }
```

**Comment by drfrag666** [comment] 2021-06-17 08:50
May be you should do a PR for Choco.

**Comment by fabiangreffrath** [comment] 2021-06-17 08:56
Yes, please!

**Comment by mikeday0** [comment] 2021-06-30 12:05
PR #1380 submitted upstream.

**Comment by fabiangreffrath** [comment] 2021-08-30 14:14
This has been fixed upstream:
https://github.com/chocolate-doom/chocolate-doom/commit/e1ac9379f676b38d2c2c003efc41b81bcfcdb29c

**Closed by fabiangreffrath** 2021-08-30 14:14 UTC
