### ISSUE TITLE
Set video_driver to "directx" and window_position to "center" in crispy-doom.cfg by default

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#119] opened 2016-06-22 19:03 UTC
I think the first one should be done for the reason of https://github.com/chocolate-doom/chocolate-doom/issues/662 and the second one for the sake of convenience :)

**Comment by fabiangreffrath** [comment] 2016-06-24 17:44
Not sure if I should deviate from Choco in this regard. I am not even sure if there will be another release based on the SDL1.2 code base...

**Comment by fabiangreffrath** [comment] 2016-06-25 21:54
Actually, this is a duplicate of https://github.com/chocolate-doom/chocolate-doom/issues/734 and I think it should be solved upstream, if at all. The discussion in this bug report is really relevant and I doubt there is much that we can add in this thread. I am closing it as a duplicate, thus.

**Closed by fabiangreffrath** 2016-06-25 21:54 UTC
