### ISSUE TITLE
Extend the savegame format to include the name of the PWAD that is necessary to load the game

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#108] opened 2016-05-30 13:24 UTC
I tried NERVE.WAD and it helped me to figure out this bug.
If you are playing Doom 2 PWAD (e.g. NERVE.WAD) and try to load a game from Doom 1 PWAD (e.g. recent E1M4B by Romero), the game doesn't exit with the error window 'Unknown tclass %d' but just freezes playing some music from some evidently random level (different for different WADs involved).

**Comment by fabiangreffrath** [comment] 2016-05-30 13:46
Chocolate Doom and thus Crispy organize their savegames in different directories per IWAD. So, how did you manage to load a Doom 1 savegame with a Doom 2 PWAD?

**Comment by Zodomaniac** [comment] 2016-05-30 14:16
Well, for me all saves are in the same directory...here's a zip file with the saves: 0 and 2 are from NERVE, and 1 is from E1M4b by Romero.
For some reason the ZIP with saves doesn't attach...

**Comment by Zodomaniac** [comment] 2016-05-30 19:08
P.S. Tested the same with Choco 2.2.1, the issue is absolutely the same.

**Comment by plumsinus** [comment] 2016-05-30 23:13
>Chocolate Doom and thus Crispy organize their savegames in different directories per IWAD. 
This appears to be the case in Linux, but not Windows. Chocolate or Crispy simply save doomsavX.dsg in the same directory as the exe.

**Comment by Zodomaniac** [comment] 2016-05-31 17:40
Updated the savegames, re-saved them after renaming the WAD to NERVE.
[upd8ed_saves.zip](https://github.com/fabiangreffrath/crispy-doom/files/291786/upd8ed_saves.zip)

**Comment by fabiangreffrath** [comment] 2016-05-31 18:48
Oh, I didn't know that the savegames are all in the same directory on Windows.

However, unfortunately, the issue you describe here is intrinsic to the Vanilla savegame format: It does not store any information about the PWAD(s) loaded and necessary to restore the savegame. I have an idea, though, how I could expand the format while still remaining Vanilla-compatible (though not -identical anymore). The engine expects an EOF marker at the end of the savegame file, but this marker is not necessarily the last byte in the file. Thus, I could add some further bytes beyond the end which could hold a string with the name of the WAD the saved level was originally from.

I am not sure if it works, but I'll have a try!

**Comment by Zodomaniac** [comment] 2016-06-03 15:55
I'd even extend this a bit: save the info about all IWAD+PWADs used in the savegame, so that if loading the save while playing some other WAD(s), the game loads the save instead of exiting with the 'Unknown tclass %d in savegame' error like now.

**Comment by fabiangreffrath** [comment] 2016-06-06 08:55
This is too huge, I am not going to invent a new savegame file format. ;) Loading PWADs upon restoring a savegame is out of question.

I just want to warn the user if he attempts to load a game for a map that the engine will be unable to reconstruct. Any additional music or graphics PWADs that were loaded when saving should be independent of this (and actually it gets on my nerves that PrBoom+ insists on warning me in such a situation).

**Comment by fabiangreffrath** [comment] 2016-10-31 07:19
Should be fixed by at least https://github.com/fabiangreffrath/crispy-doom/commit/9b2126d55a74b7402e09035dd2057a2de1a1e5b4

**Closed by fabiangreffrath** 2016-10-31 07:19 UTC
Labels: enhancement

**Comment by Zodomaniac** [comment] 2016-11-02 06:56
Now the game exits in case of trying to load a savegame of a different PWAD and/or IWAD. Is that the intended behavior?

**Comment by Zodomaniac** [comment] 2016-11-02 07:44
I still manage to freeze the game. Extract these WADs and saves, launch Batman Doom with -merge batman_fixed.wad -deh batman_mod.deh and try to load the 3rd savegame (doomsav2.dsg).
[Saves&WADs.zip](https://github.com/fabiangreffrath/crispy-doom/files/565904/Saves.WADs.zip)

**Comment by fabiangreffrath** [comment] 2016-11-02 08:10
Thanks for testing this feature! Please note that this only works for new savegames. It still isn't possible to magically detect the necessary PWAD from old savegames that were saved before this feature existed.

Can you confirm that it works if you re-save your savegame with the proper PWAD loaded and try to load it with just the IWAD loaded?

**Comment by fabiangreffrath** [comment] 2016-11-02 08:11
Also, be sure to grab a build that has this commit applied:
https://github.com/fabiangreffrath/crispy-doom/commit/ac4a91881a59942df2bdd41a1707ec7e77ee3980

**Comment by Zodomaniac** [comment] 2016-11-02 09:34
>Please note that this only works for new savegames. It still isn't possible to magically detect the necessary PWAD from old savegames that were saved before this feature existed.

I did re-save the game before testing :)

**Comment by fabiangreffrath** [comment] 2016-11-02 10:10
That's strange, because the savegames you sent me are missing the extra information at the end of the files. Do you have the feature enabled at all? It's under Crispness/Tactical on page 2.

**Comment by Zodomaniac** [comment] 2016-11-02 10:11
>Do you have the feature enabled at all? It's under Crispness/Tactical on page 2.

Oh! I totally didn't know I have to enable it!

**Comment by fabiangreffrath** [comment] 2016-11-02 10:21
You shouldn't have to, it's the only option that's enabled by default. However, something seems to be strange about the Crispy auto-builder. I'll have to contact @fragglet about that.

**Comment by fabiangreffrath** [comment] 2016-11-02 18:56
Daily builds should be fine again, thanks @fragglet !

**Comment by Zodomaniac** [comment] 2016-11-03 07:05
>Daily builds should be fine again, thanks @fragglet !

Yes, they are! Nicely done!

**Comment by fabiangreffrath** [comment] 2016-11-03 07:43
So, could you confirm that the extended savegame feature now works as intended?

**Comment by Zodomaniac** [comment] 2016-11-03 07:53
I still notice a bug: if I try lo load a savegame from Vanilla Doom 2 while playing Batman Doom and reply Y to the Continue? question, the game freezes. Both saves are extended.
[Batman 5 D2 6.zip](https://github.com/fabiangreffrath/crispy-doom/files/568397/Batman.5.D2.6.zip)

**Comment by fabiangreffrath** [comment] 2016-11-03 07:59
How is this a bug? You have been warned that the WADs you have loaded and the WADs that are required to properly restore the savegame don't match, but you decided to continue loading. This will lead to a crash, there is nothing more I could do about that than obeying the player's decision.

**Comment by Zodomaniac** [comment] 2016-11-03 08:00
OK, let it be.

**Comment by fabiangreffrath** [comment] 2016-11-03 08:06
Ah, I see, it shoudn't freeze. But this is (most probably) not a bug in the extended savegames implementation. I should investigate it further, though. Would you mind opening a separate issue for this and provide your eamples there? Thank you!

**Comment by Zodomaniac** [comment] 2016-11-03 08:10
Opened a separate issue
https://github.com/fabiangreffrath/crispy-doom/issues/130

**Comment by fabiangreffrath** [comment] 2016-11-03 10:59
Thanks!
